// Generated by npm run build:ui-icons from src/data/ui-icons.json.
window.Pattove.iconAssets = {
  "arrow": {
    "entry": "ICO-445",
    "src": "assets/icons/ui/arrow.webp"
  },
  "bell": {
    "entry": "ICO-100",
    "src": "assets/icons/ui/bell.webp"
  },
  "bookmark": {
    "entry": "ICO-119",
    "src": "assets/icons/ui/bookmark.webp"
  },
  "box": {
    "entry": "lucide:box",
    "src": "assets/icons/ui/box.webp"
  },
  "check": {
    "entry": "ICO-122",
    "src": "assets/icons/ui/check.webp"
  },
  "chevron-down": {
    "entry": "ICO-453",
    "src": "assets/icons/ui/chevron-down.webp"
  },
  "chevron": {
    "entry": "ICO-455",
    "src": "assets/icons/ui/chevron.webp"
  },
  "close": {
    "entry": "ICO-08",
    "src": "assets/icons/ui/close.webp"
  },
  "compass": {
    "entry": "ICO-327",
    "src": "assets/icons/ui/compass.webp"
  },
  "edit": {
    "entry": "ICO-30",
    "src": "assets/icons/ui/edit.webp"
  },
  "file": {
    "entry": "ICO-167",
    "src": "assets/icons/ui/file.webp"
  },
  "folder": {
    "entry": "ICO-169",
    "src": "assets/icons/ui/folder.webp"
  },
  "grid": {
    "entry": "ICO-256",
    "src": "assets/icons/ui/grid.webp"
  },
  "group-domain": {
    "entry": "ICO-331",
    "src": "assets/icons/ui/group-domain.webp"
  },
  "group-expression": {
    "entry": "ICO-699",
    "src": "assets/icons/ui/group-expression.webp"
  },
  "group-game": {
    "entry": "lucide:gamepad-2",
    "src": "assets/icons/ui/group-game.webp"
  },
  "group-interaction": {
    "entry": "lucide:mouse-pointer-2",
    "src": "assets/icons/ui/group-interaction.webp"
  },
  "group-quality": {
    "entry": "ICO-645",
    "src": "assets/icons/ui/group-quality.webp"
  },
  "group-service": {
    "entry": "ICO-398",
    "src": "assets/icons/ui/group-service.webp"
  },
  "group-vocabulary": {
    "entry": "ICO-1086",
    "src": "assets/icons/ui/group-vocabulary.webp"
  },
  "group-work": {
    "entry": "lucide:briefcase-business",
    "src": "assets/icons/ui/group-work.webp"
  },
  "info": {
    "entry": "ICO-94",
    "src": "assets/icons/ui/info.webp"
  },
  "layers": {
    "entry": "ICO-280",
    "src": "assets/icons/ui/layers.webp"
  },
  "menu": {
    "entry": "ICO-05",
    "src": "assets/icons/ui/menu.webp"
  },
  "plus": {
    "entry": "ICO-25",
    "src": "assets/icons/ui/plus.webp"
  },
  "rotate": {
    "entry": "ICO-40",
    "src": "assets/icons/ui/rotate.webp"
  },
  "search": {
    "entry": "ICO-62",
    "src": "assets/icons/ui/search.webp"
  },
  "shapes": {
    "entry": "ICO-704",
    "src": "assets/icons/ui/shapes.webp"
  },
  "upload": {
    "entry": "ICO-48",
    "src": "assets/icons/ui/upload.webp"
  },
  "warning": {
    "entry": "ICO-96",
    "src": "assets/icons/ui/warning.webp"
  },
  "copy": {
    "entry": "ICO-34",
    "src": "assets/icons/ui/copy.webp"
  },
  "download": {
    "entry": "ICO-47",
    "src": "assets/icons/ui/download.webp"
  },
  "first": {
    "entry": "ICO-20",
    "src": "assets/icons/ui/first.webp"
  },
  "last": {
    "entry": "ICO-21",
    "src": "assets/icons/ui/last.webp"
  },
  "chevron-left": {
    "entry": "ICO-454",
    "src": "assets/icons/ui/chevron-left.webp"
  },
  "image": {
    "entry": "ICO-592",
    "src": "assets/icons/ui/image.webp"
  },
  "minus": {
    "entry": "ICO-531",
    "src": "assets/icons/ui/minus.webp"
  }
};
window.Pattove.uiIcon = (name, extraClass = '') => {
  const asset = window.Pattove.iconAssets[name];
  if (!asset) return '';
  const classes = String(extraClass).replace(/[^a-zA-Z0-9_ -]/g, '');
  return '<img class="ui-icon' + (classes ? ' ' + classes : '') + '" src="' + asset.src + '" data-ui-icon="' + name + '" data-illustration="' + asset.entry + '" width="24" height="24" alt="" aria-hidden="true" draggable="false" decoding="async">';
};
window.Pattove.iconMarkup = Object.fromEntries(Object.keys(window.Pattove.iconAssets).map(name => [name, window.Pattove.uiIcon(name)]));
