import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';
import crypto from 'node:crypto';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = name => fs.readFileSync(path.join(root, name), 'utf8');
const css = read('src/system/parts.css');
const blocks = {};
for (const match of css.matchAll(/\/\* @part ([\w-]+) \*\/([\s\S]*?)(?=\/\* @part |$)/g)) {
  if (blocks[match[1]]) throw new Error('Duplicate CSS block: ' + match[1]);
  blocks[match[1]] = match[2].trim();
}
const context = vm.createContext({ window: {} });
for (const file of ['src/data/catalog.js','src/ui/icons.js','src/system/registry.js','src/system/parts.js']) vm.runInContext(read(file), context, { filename: file });
const registry = context.window.Pattove.systemRegistry;
const ids = new Set();
for (const item of registry.items) {
  if (ids.has(item.id)) throw new Error('Duplicate implementation: ' + item.id);
  ids.add(item.id);
  if (!['Token','Primitive','Atom','Molecule','Module','Template','Page'].includes(item.layer)) throw new Error('Invalid layer: ' + item.id);
  if (!['Trial','Stable','Deprecated'].includes(item.lifecycle)) throw new Error('Invalid lifecycle: ' + item.id);
  if (!/^\d+\.\d+\.\d+$/.test(item.version)) throw new Error('Invalid version: ' + item.id);
  if (item.lifecycle === 'Deprecated' && !item.replacement) throw new Error('Missing replacement: ' + item.id);
  for (const key of ['id','name','layer','purpose','compatibility','source','version','lifecycle']) if (!item[key]) throw new Error(item.id + ': missing ' + key);
  if (!fs.existsSync(path.join(root,item.source))) throw new Error('Missing source: ' + item.source);
  for (const block of item.css) if (!blocks[block]) throw new Error(item.id + ': missing CSS ' + block);
  const visit = (id, ancestors = []) => {
    if (ancestors.includes(id)) throw new Error('Dependency cycle: ' + [...ancestors,id].join(' → '));
    const target = registry.index.get(id);
    if (!target) throw new Error('Missing dependency: ' + id);
    target.deps.forEach(dep => visit(dep,[...ancestors,id]));
  };
  visit(item.id);
  context.window.Pattove.parts.renderItem(item.id, 'build-check', registry.normalizeOptions(item.id));
  for (const control of item.controls) for (const [value] of control.values) context.window.Pattove.parts.renderItem(item.id, 'build-check', registry.normalizeOptions(item.id,{[control.key]:value}));
}
const sources = ['src/system/parts.js','src/system/parts.css','src/system/behaviors.js','src/system/export.js','src/system/registry.js','src/data/catalog.js','src/styles/tokens.css','src/styles/themes.css'];
const revision = crypto.createHash('sha256').update(sources.map(file => file + '\0' + read(file)).join('\0')).digest('hex');
fs.writeFileSync(path.join(root, 'src/data/system-registry.json'), JSON.stringify({ version: registry.version, revision, sources, sections: registry.sections, items: registry.items, patterns: registry.patterns }, null, 2) + '\n');
fs.writeFileSync(path.join(root, 'src/data/system-source.js'), '// Generated by npm run build:system.\nwindow.Pattove.systemSource = ' + JSON.stringify(blocks) + ';\nwindow.Pattove.systemSourceRevision = ' + JSON.stringify(revision) + ';\n');
const fonts = {};
for (const [name, file, license] of [
  ['Pretendard', 'PretendardVariable.woff2', 'Pretendard-LICENSE.txt'],
  ['Outfit', 'Outfit-Variable.woff2', 'Outfit-OFL.txt']
]) {
  fonts[name] = { data: fs.readFileSync(path.join(root, 'assets/fonts', file)).toString('base64'), license: read('assets/fonts/' + license) };
}
fs.writeFileSync(path.join(root, 'src/data/system-fonts.js'), '// Generated; loaded only when exporting a standalone HTML.\nwindow.Pattove.systemFonts = ' + JSON.stringify(fonts) + ';\n');
console.log('System CSS blocks: ' + Object.keys(blocks).length + '; offline font bundle generated.');
