'use client';
import React,{useCallback,useEffect,useId,useRef,useState} from 'react';
import {LayoutWorkContent} from './layout-work-content.jsx';
export function FloatingPanel({children=<LayoutWorkContent/>,title='산책 기록',onChange}){
 const id=useId(),host=useRef(null),panel=useRef(null),drag=useRef(null),position=useRef({x:0,y:0}),[point,setPoint]=useState(position.current),change=useRef(onChange);change.current=onChange;
 const move=useCallback((x,y)=>{const h=host.current,p=panel.current;if(!h||!p)return;const next={x:Math.min(Math.max(0,x),Math.max(0,h.clientWidth-p.offsetWidth)),y:Math.min(Math.max(0,y),Math.max(0,h.clientHeight-p.offsetHeight))};position.current=next;setPoint(next);change.current?.(next);},[]);
 useEffect(()=>{const resize=()=>move(position.current.x,position.current.y),observer=new ResizeObserver(resize);observer.observe(host.current);observer.observe(panel.current);return()=>observer.disconnect();},[move]);
 return <div className="ds-layout ds-floating-panel"><div ref={host} className="ds-layout-float-host"><div ref={panel} className="ds-layout-float" role="dialog" aria-modal={false} aria-labelledby={id+'-title'} style={{transform:'translate('+point.x+'px,'+point.y+'px)'}}><header><h2 id={id+'-title'}>{title}</h2><button type="button" className="ds-layout-control" data-layout-drag aria-describedby={id+'-help'} onKeyDown={e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home'].includes(e.key))return;e.preventDefault();const step=e.shiftKey?40:10;move(e.key==='Home'?0:point.x+(e.key==='ArrowRight'?step:e.key==='ArrowLeft'?-step:0),e.key==='Home'?0:point.y+(e.key==='ArrowDown'?step:e.key==='ArrowUp'?-step:0));}} onPointerDown={e=>{if(e.button!==0)return;e.preventDefault();e.currentTarget.focus();e.currentTarget.setPointerCapture(e.pointerId);drag.current={pointer:e.pointerId,x:e.clientX,y:e.clientY,startX:point.x,startY:point.y};}} onPointerMove={e=>{const d=drag.current;if(d?.pointer===e.pointerId)move(d.startX+e.clientX-d.x,d.startY+e.clientY-d.y);}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}} onLostPointerCapture={()=>{drag.current=null;}}>위치 조절</button></header><span id={id+'-help'} className="ds-layout-sr">방향키로 이동하고 Home으로 원래 위치로 돌아갑니다.</span>{children}</div></div></div>;
}
