'use client';
import React from 'react';
import {safeLink} from './safe-link.jsx';
export const navigationLinks=[{label:'산책',href:'#walks'},{label:'기록',href:'#notes'},{label:'모임',href:'#group'}];
export const navigationGroups=[{label:'산책',href:'#walks',children:[{label:'숲길',href:'#forest'},{label:'물가',href:'#river'}]},{label:'기록',href:'#notes',children:[{label:'여행기',href:'#journals'},{label:'사진',href:'#photos'}]}];
export const navigationSteps=[{label:'기본 정보',href:'#information',description:'이름과 연락처를 입력합니다.'},{label:'일정 선택',href:'#schedule',description:'참여할 날짜를 고릅니다.'},{label:'신청 확인',description:'입력한 내용을 확인하고 제출합니다.'}];
export function NavigationLinks({items=navigationLinks,current,rail=false,skipParents=false}){return <ul className="ds-nav-links">{items.map((item,i)=>{const target=skipParents?(item.children?.[0]??item):item;return <li key={item.id??i}><a href={safeLink(target.href)} aria-current={current===target.href?'page':undefined} aria-label={rail?item.label:undefined}>{rail&&<span aria-hidden="true" className="ds-nav-symbol">{item.icon??item.label.slice(0,1)}</span>}<span>{item.label}</span></a></li>;})}</ul>;}
export function NavigationTree({items=navigationGroups,current,toggle=false,depth=0}){if(depth>20)throw Error('Navigation depth must not exceed 20');return <ul className="ds-nav-tree">{items.map((item,i)=><li key={item.id??i}><a href={safeLink(item.href)} aria-current={current===item.href?'page':undefined}>{item.label}</a>{item.children?.length>0&&(toggle?<NavigationDisclosure label={item.label+' 하위 항목'}><NavigationTree items={item.children} current={current} toggle depth={depth+1}/></NavigationDisclosure>:<NavigationTree items={item.children} current={current} depth={depth+1}/>)}</li>)}</ul>;}
export function NavigationDisclosure({label='메뉴',children,className=''}){return <details className={'ds-nav-disclosure '+className} onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();const node=e.currentTarget;node.open=false;node.querySelector(':scope > summary')?.focus();}}} onBlur={e=>{if(e.relatedTarget&&!e.currentTarget.contains(e.relatedTarget))e.currentTarget.open=false;}}><summary>{label}</summary>{children}</details>;}
export function AnchorJump({targetId,children='본문으로 이동',className=''}){return <a className={'ds-nav-jump '+className} href={'#'+encodeURIComponent(targetId)} onClick={()=>{const target=document.getElementById(targetId);if(target){if(!target.hasAttribute('tabindex'))target.tabIndex=-1;target.focus({preventScroll:true});}}}>{children}</a>;}
