const { chromium } = require('playwright-core');
const { pathToFileURL } = require('node:url');
const path = require('node:path');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const url = pathToFileURL(path.resolve(__dirname, '../index.html')).href;
const checks = [];
const check = (name, value) => { assert.ok(value, name); checks.push(name); };
(async () => {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  page.setDefaultTimeout(5000);
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  const count = () => page.locator('.pattern-card').count();
  const close = async () => { await page.keyboard.press('Escape'); await page.waitForFunction(() => !document.querySelector('#detail-dialog').open); };
  try {
    await page.goto(url);
    check('첫 진입은 스타일 세 가지', await page.locator('.style-card').count() === 3 && page.url().endsWith('#/styles'));
    check('실제 로고 정본 로드', await page.locator('.brand img').evaluate(i => i.complete && i.naturalWidth > 0));
    await page.locator('[data-apply-style="ink"]').click();
    check('선택한 스타일의 패턴 12개', await count() === 12 && await page.locator('.pattern-card .theme-ink').count() === 12);
    await page.locator('[data-category="input"]').click();
    check('목적 분류로 좁히기', await count() === 2);
    await page.locator('#style-switch').click();
    await page.locator('[data-apply-style="block"]').click();
    check('스타일을 바꿔도 분류 유지', await count() === 2 && await page.locator('.pattern-card .theme-block').count() === 2);
    await page.reload();
    check('선택한 스타일과 분류 새로고침 유지', await count() === 2 && await page.locator('.pattern-card .theme-block').count() === 2);
    await page.locator('[data-category="all"]').click();
    await page.keyboard.press('/');
    check('슬래시로 검색 초점', await page.locator('#query').evaluate(e => e === document.activeElement));
    await page.locator('#query').fill('저장 완료');
    check('실제 일치 항목 제안', await page.locator('.search-suggestion').count() === 2);
    await page.locator('#query').press('ArrowUp');
    check('위 방향키로 마지막 제안 선택', await page.locator('#suggestion-1').getAttribute('aria-selected') === 'true');
    await page.locator('#query').press('Enter');
    check('제안에서 현재 스타일 상세 열림', await page.locator('#detail-dialog .preview.theme-block').count() === 1);
    await close();
    check('상세를 닫으면 검색 초점 복귀', await page.locator('#query').evaluate(e => e === document.activeElement));
    await page.locator('#query').fill('저장 완료');
    await page.locator('#query').press('Enter');
    check('검색 결과 2개', await count() === 2);
    await page.locator('#style-switch').click();
    await page.locator('[data-apply-style="landscape"]').click();
    check('스타일 전환 시 검색 조건 유지', await count() === 2 && await page.locator('#query').inputValue() === '저장 완료');
    await page.locator('[data-action="clear-query"]').click();
    check('검색 조건 해제', await count() === 12);
    await page.locator('[data-quick-save="tabs"]').click();
    check('카드 바로 저장', await page.locator('[data-quick-save="tabs"]').getAttribute('aria-pressed') === 'true');
    await page.reload();
    check('저장 새로고침 유지', await page.locator('[data-quick-save="tabs"]').getAttribute('aria-pressed') === 'true');
    await page.locator('[data-open="toast"]').click();
    check('상세 제목으로 초점', await page.locator('#detail-title').evaluate(e => e === document.activeElement));
    check('본문은 미작성 자리', await page.locator('.pending-copy').count() === 2);
    check('상세에는 개별 스타일 변경이 없음', await page.locator('[data-detail-style]').count() === 0);
    await page.locator('[data-save="toast"]').click();
    check('상세에서 현재 스타일 저장', await page.locator('[data-save="toast"]').getAttribute('aria-pressed') === 'true');
    check('저장 후 조작 초점 유지', await page.locator('[data-save="toast"]').evaluate(e => e === document.activeElement));
    for (let i = 0; i < 10; i++) await page.keyboard.press('Tab');
    check('상세 대화상자 초점 가두기', await page.evaluate(() => !!document.activeElement.closest('dialog[open]')));
    await close();
    check('상세를 닫으면 카드로 복귀', await page.locator('[data-open="toast"]').evaluate(e => e === document.activeElement));
    await page.locator('#style-switch').click();
    await page.locator('[data-apply-style="ink"]').click();
    await page.locator('[data-quick-save="tabs"]').click();
    await page.locator('#saved-link').click();
    check('저장은 스타일별로 묶음', await count() === 3 && await page.locator('.saved-group').count() === 2);
    await page.locator('#query').fill('탭');
    await page.locator('#query').press('Enter');
    check('저장한 패턴 내 검색', await count() === 2 && await page.locator('body').getAttribute('data-page') === 'saved');
    await page.locator('[data-remove="tabs"][data-style="ink"]').click();
    check('저장 해제', await count() === 1);
    await page.locator('[data-action="undo-save"]').click();
    check('해제 되돌리기', await count() === 2);
    await page.reload();
    check('되돌리기 저장 유지', await count() === 2);
    await page.locator('.brand').click();
    check('로고에서 스타일 입구로', await page.locator('.style-card').count() === 3);
    await page.locator('[data-apply-style="block"]').click();
    await page.goBack();
    check('브라우저 뒤로 가기', await page.locator('.style-card').count() === 3);
    await page.goForward();
    check('브라우저 앞으로 가기', await count() === 12 && await page.locator('.theme-block.preview').count() === 12);
    await page.locator('#query').fill('<img src=x onerror=alert(1)>');
    await page.locator('#query').press('Enter');
    check('검색어 HTML 미실행, 빈 결과', await count() === 0 && await page.locator('.empty-state').isVisible());
    await page.locator('[data-action="reset"]').click();
    check('빈 결과에서 복귀', await count() === 12);
    await page.goto(url + '#/patterns?style=ink&view=list&sort=name&compare=toast,tabs');
    check('옛 목록·비교 주소는 그리드로 정리', await count() === 12 && !page.url().includes('view=') && !page.url().includes('compare=') && !(await page.locator('dialog[open]').count()));
    await page.goto(url + '#/patterns?style=landscape&detail=tabs');
    check('상세 직접 주소', await page.locator('#detail-dialog').isVisible());
    await close();
    check('직접 주소를 닫아도 스타일 유지', await page.locator('.pattern-card .theme-landscape').count() === 12);
    const broken = await browser.newContext();
    await broken.addInitScript(() => localStorage.setItem('pattove-shell:v1', JSON.stringify({ saved: [null, {}, { id: 'missing', style: 'base' }], style: 'wrong' })));
    const brokenPage = await broken.newPage();
    await brokenPage.goto(url + '#/saved');
    check('손상된 저장 데이터 무시', await brokenPage.locator('.empty-state').isVisible());
    await broken.close();
    const blocked = await browser.newContext();
    await blocked.addInitScript(() => { Object.defineProperty(window, 'localStorage', { get() { throw new Error('blocked'); } }); });
    const blockedPage = await blocked.newPage();
    await blockedPage.goto(url + '#/patterns?style=ink');
    await blockedPage.locator('[data-quick-save="toast"]').click();
    check('저장소 차단에도 세션 저장 가능', await blockedPage.locator('[data-quick-save="toast"]').getAttribute('aria-pressed') === 'true');
    check('저장소 차단을 알려줌', (await blockedPage.locator('#notice-text').textContent()).includes('지금 열린 화면'));
    await blockedPage.locator('[data-open="tabs"]').click();
    await blockedPage.locator('[data-save="tabs"]').click();
    check('모달 안에서도 저장소 차단 표시', await blockedPage.locator('#detail-dialog .save-status').isVisible());
    await blocked.close();
    check('브라우저 오류 없음', errors.length === 0);
    fs.mkdirSync('test-results/lean', { recursive: true });
    fs.writeFileSync('test-results/lean/functional.json', JSON.stringify({ checks, errors }, null, 2));
    console.log(checks.length + ' checks passed.');
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; });

