const CATEGORIES = [
  ['all','모든 패턴','grid'],['navigate','이동하기','compass'],['input','입력받기','edit'],['browse','정보 살펴보기','layers'],['feedback','결과 알리기','bell'],['recover','작업 이어가기','rotate']
];
const STYLES = {
  clear:{name:'또렷한 기본',description:'정보가 많은 도구와 업무 화면에',detail:'고딕 · 촘촘한 간격 · 파랑 · 작은 곡선',ref:'shadcn의 부품 위계와 KAWAI의 미니어처 구조'},
  ink:{name:'잉크 노트',description:'콘텐츠와 개성을 또렷하게 보여줄 때',detail:'명조 제목 · 먹선 · 크림 · 단단한 버튼',ref:'영감보관함의 Karita 선화와 MYTURN 격자'},
  calm:{name:'고요한 색면',description:'차분하게 읽고 선택하는 화면에',detail:'넉넉한 간격 · 녹색 면 · 부드러운 곡선',ref:'영감보관함의 바다 홈화면과 제한색 포스터'}
};
const PATTERNS = [
 {id:'toast',source:'STA-03',name:'잠깐 알림',en:'Toast',cat:'feedback',status:['success'],type:'toast',task:'저장처럼 가벼운 작업의 완료를 알려요.',search:'저장 완료 끝났 끝났다고 성공 알려 알리기 알림 토스트 snackbar',why:'저장 성공처럼 흐름을 끊지 않아도 되는 결과에 맞아요.',when:'저장·복사처럼 결과가 짧고, 놓쳐도 다시 확인할 수 있을 때',avoid:'결제 실패나 동의처럼 반드시 읽거나 결정해야 할 때',confirm:'필요 없음',placement:'화면 가장자리, 잠깐',caution:'중요한 정보의 유일한 전달 수단으로 쓰지 않아요.',alternatives:['banner','dialog'],device:['web','mobile']},
 {id:'banner',source:'STA-02',name:'계속 보이는 안내',en:'Inline alert',cat:'feedback',status:['success','error'],type:'banner',task:'중요한 안내를 내용 곁에 남겨 둬요.',search:'저장 완료 성공 알려 알리기 알림 중요 계속 배너 인라인 alert',why:'놓치지 않고 다시 읽어야 하는 안내라면 더 적합해요.',when:'이용 제한·저장 실패 등 읽고 대응할 내용을 남겨야 할 때',avoid:'매번 반복되는 가벼운 완료 알림으로 화면을 채울 때',confirm:'읽거나 해결할 때까지 유지',placement:'관련 내용 바로 위',caution:'무엇이 달라졌고 어떻게 해결할지 함께 적어요.',alternatives:['toast','dialog'],device:['web','mobile']},
 {id:'dialog',source:'ACT-08',name:'확인받기',en:'Dialog',cat:'feedback',status:['normal'],type:'dialog',task:'진행하기 전에 사용자의 결정을 받아요.',search:'삭제 위험 확인 결정 중요 알려 알리기 모달 다이얼로그 dialog',why:'알리기만 하는 상황보다, 선택이나 확인이 필요한 상황에 맞아요.',when:'되돌리기 어려운 작업 전에 영향과 선택을 확인할 때',avoid:'단순 저장 성공을 알리려고 작업을 중단시킬 때',confirm:'명시적인 선택 필요',placement:'화면 중앙 또는 하단',caution:'닫은 뒤 원래 작업 위치와 초점을 되돌려 줘요.',alternatives:['toast','banner'],device:['web','mobile']},
 {id:'progress',source:'STA-05',name:'진행 상황 보여주기',en:'Progress',cat:'feedback',status:['loading'],type:'progress',task:'작업이 얼마나 진행됐는지 알려요.',search:'업로드 진행 기다 로딩 얼마나 남았 퍼센트 progress',when:'전체량과 완료량을 실제로 계산할 수 있을 때',avoid:'진행률을 알 수 없는데 임의의 숫자를 표시할 때',confirm:'필요 없음',placement:'진행 중인 작업 곁',caution:'취소 가능 여부와 오래 걸릴 때의 안내를 마련해요.',alternatives:['skeleton','banner'],device:['web','mobile']},
 {id:'skeleton',source:'STA-04',name:'불러올 자리 보여주기',en:'Skeleton',cat:'feedback',status:['loading'],type:'skeleton',task:'내용을 기다리는 동안 화면 구조를 보여줘요.',search:'기다 로딩 불러 skeleton 스켈레톤 자리',when:'곧 나타날 내용의 형태와 배치를 알고 있을 때',avoid:'오래 멈췄는데 추가 설명 없이 계속 반짝일 때',confirm:'필요 없음',placement:'콘텐츠가 나타날 자리',caution:'실패하면 기다림을 끝내고 복구 방법을 보여줘요.',alternatives:['progress','error'],device:['web','mobile']},
 {id:'empty',source:'STA-06',name:'빈 화면 안내하기',en:'Empty state',cat:'recover',status:['empty'],type:'empty',task:'내용이 없는 이유와 다음 행동을 알려요.',search:'처음 내용 없는 화면 비어 빈 화면 결과 없음 empty',when:'처음 사용하거나 검색 조건에 맞는 항목이 없을 때',avoid:'불러오기 실패를 내용이 없는 상태처럼 표시할 때',confirm:'다음 행동을 선택',placement:'비어 있는 콘텐츠 자리',caution:'처음 사용·검색 결과 없음·모두 완료를 구분해요.',alternatives:['error','skeleton'],device:['web','mobile']},
 {id:'error',source:'STA-08',name:'실패 후 다시 시도하기',en:'Retry',cat:'recover',status:['error'],type:'error',task:'입력한 내용을 지키며 다시 시도하게 해요.',search:'실패 오류 재시도 다시 네트워크 저장 안됨 복구 error retry',when:'네트워크 등 복구 가능한 이유로 작업이 실패했을 때',avoid:'입력을 전부 지우고 처음부터 다시 하게 만들 때',confirm:'재시도 선택',placement:'실패한 작업 곁',caution:'반복 실패할 때 대안과 도움받을 경로를 제공해요.',alternatives:['banner','empty'],device:['web','mobile']},
 {id:'undo',source:'STA-09',name:'방금 한 작업 되돌리기',en:'Undo',cat:'recover',status:['success'],type:'undo',task:'실수로 바꾼 내용을 복구하게 해요.',search:'삭제 취소 되돌리기 실수 복구 undo',when:'삭제·이동처럼 직전 변경을 실제로 복원할 수 있을 때',avoid:'복원할 수 없는 작업에 되돌리기 버튼을 보여줄 때',confirm:'원하면 취소',placement:'결과 안내 곁',caution:'취소 가능한 시간과 영향을 명확하게 해요.',alternatives:['dialog','toast'],device:['web','mobile']},
 {id:'pagination',source:'NAV-10',name:'페이지로 나누기',en:'Pagination',cat:'browse',status:['normal'],type:'pagination',task:'목록의 위치를 기억하고 다시 찾아가요.',search:'많은 항목 나눠 보여 목록 페이지 페이지네이션 pagination',why:'특정 위치로 돌아오거나 목록을 꼼꼼히 확인할 때 맞아요.',when:'검색 결과·관리 목록처럼 위치와 끝을 알아야 할 때',avoid:'가벼운 콘텐츠를 끊김 없이 둘러보는 흐름이 중요한 때',confirm:'다음 페이지 선택',placement:'목록 위 또는 아래',caution:'페이지를 바꿔도 정렬·검색 조건을 유지해요.',alternatives:['infinite','search'],device:['web','mobile']},
 {id:'infinite',source:'NAV-11',name:'계속 이어서 보기',en:'Infinite scroll',cat:'browse',status:['normal','loading'],type:'infinite',task:'스크롤하면서 콘텐츠를 더 살펴봐요.',search:'많은 항목 나눠 보여 목록 더보기 무한 스크롤 infinite',why:'정해진 항목보다 새로운 콘텐츠를 계속 발견할 때 맞아요.',when:'사진·피드처럼 가볍게 탐색하는 흐름일 때',avoid:'특정 위치를 기억하거나 목록 끝에 도달해야 할 때',confirm:'스크롤 또는 더 보기',placement:'목록 마지막',caution:'돌아왔을 때 위치를 복원하고 더 보기 대안을 제공해요.',alternatives:['pagination','search'],device:['web','mobile']},
 {id:'tabs',source:'NAV-06',name:'같은 자리에서 전환하기',en:'Tabs',cat:'navigate',status:['normal'],type:'tabs',task:'관련된 내용을 한 자리에서 바꿔 봐요.',search:'탭 전환 화면 오가기 tabs',when:'동등한 수준의 관련 내용을 번갈아 볼 때',avoid:'순서대로 완료해야 하는 단계를 탭으로 위장할 때',confirm:'탭 선택',placement:'내용 바로 위',caution:'선택 상태와 키보드 이동 규칙을 함께 제공해요.',alternatives:['accordion','stepper'],device:['web','mobile']},
 {id:'drawer',source:'NAV-42',name:'옆에서 메뉴 열기',en:'Drawer',cat:'navigate',status:['normal'],type:'drawer',task:'필요할 때 보조 메뉴를 꺼내요.',search:'모바일 메뉴 사이드바 드로어 drawer 이동',when:'화면 공간이 좁고 보조 메뉴를 잠시 열어야 할 때',avoid:'항상 비교하며 봐야 하는 주요 정보를 숨길 때',confirm:'열기와 닫기',placement:'화면 가장자리',caution:'닫기 버튼과 원래 자리로 돌아갈 경로를 보여줘요.',alternatives:['tabs','accordion'],device:['web','mobile']},
 {id:'accordion',source:'EDT-13',name:'필요한 내용 펼치기',en:'Accordion',cat:'browse',status:['normal'],type:'accordion',task:'긴 내용 중 궁금한 부분만 펼쳐 봐요.',search:'접기 펼치기 질문 도움말 아코디언 accordion',when:'질문과 답처럼 제목만으로 내용을 짐작할 수 있을 때',avoid:'반드시 읽어야 할 핵심 내용을 숨길 때',confirm:'열고 닫기',placement:'해당 제목 아래',caution:'펼친 상태가 색 외에도 기호와 구조로 보여야 해요.',alternatives:['tabs','search'],device:['web','mobile']},
 {id:'form',source:'STA-07',name:'입력한 자리에서 고치기',en:'Inline validation',cat:'input',status:['normal','error'],type:'form',task:'잘못 입력한 곳과 고칠 방법을 알려요.',search:'입력 오류 이메일 잘못 폼 유효성 validation form',when:'어느 입력을 어떻게 수정할지 바로 안내할 수 있을 때',avoid:'입력을 시작하자마자 오류로 몰아붙일 때',confirm:'내용 수정',placement:'입력 필드 바로 아래',caution:'오류 문구와 필드를 연결하고 기존 입력을 보존해요.',alternatives:['banner','stepper'],device:['web','mobile']},
 {id:'search',source:'DAT-01',name:'조건으로 좁혀 찾기',en:'Search & filter',cat:'browse',status:['normal','empty'],type:'search',task:'많은 항목에서 필요한 것만 골라 봐요.',search:'검색 찾기 조건 필터 많은 항목 목록 search filter',when:'이름이나 조건으로 후보를 좁힐 수 있을 때',avoid:'필터가 켜진 사실과 해제 방법이 보이지 않을 때',confirm:'검색어나 조건 입력',placement:'목록 위',caution:'검색 결과가 없을 때 조건을 바꾸는 방법을 보여줘요.',alternatives:['pagination','empty'],device:['web','mobile']},
 {id:'stepper',source:'INP-19',name:'입력을 단계로 나누기',en:'Stepper',cat:'input',status:['normal'],type:'stepper',task:'긴 입력을 이해할 수 있는 순서로 나눠요.',search:'입력 단계 긴 폼 여러 화면 순서 stepper',when:'복잡한 입력을 의미 있는 단계로 나눌 수 있을 때',avoid:'짧은 입력에 불필요한 다음 버튼을 반복할 때',confirm:'단계별 진행',placement:'입력 화면 위',caution:'이전 단계로 돌아가도 입력을 유지해요.',alternatives:['form','tabs'],device:['web','mobile']}
];
