const {chromium}=require('/opt/homebrew/lib/node_modules/playwright');
const {pathToFileURL}=require('node:url');
const path=require('node:path');
const fs=require('node:fs');
const assert=require('node:assert/strict');
const base=__dirname;
const checks=[];
function check(label,condition){assert.ok(condition,label);checks.push(label);}
(async()=>{
 const browser=await chromium.launch({headless:true});
 try{
  const context=await browser.newContext({viewport:{width:1440,height:1080},deviceScaleFactor:1});
  const page=await context.newPage();page.setDefaultTimeout(6000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(pathToFileURL(path.join(base,'index.html')).href);
  check('첫 화면의 대표 패턴 16개',await page.locator('.pattern-card').count()===16);
  const before=await page.evaluate(()=>({visibleText:document.body.innerText.replace(/\s/g,'').length,firstPreviewTop:document.querySelector('.preview').getBoundingClientRect().top,visibleCards:[...document.querySelectorAll('.pattern-card')].filter(e=>{const r=e.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight}).length}));
  await page.screenshot({path:path.join(base,'02-패턴-탐색.png')});
  await page.locator('#query').focus();check('검색 예시는 검색창 초점에서 노출',await page.locator('#search-suggestions').isVisible());
  await page.locator('[data-query="입력 오류"]').click();check('상황 예시 선택으로 입력 오류 발견',await page.locator('[data-pattern="form"]').count()===1);
  await page.locator('#reset-filters').click();
  await page.locator('#query').fill('저장이 끝났다고 알려주고 싶어요');await page.locator('#search-form').evaluate(f=>f.requestSubmit());
  check('상황 검색에서 토스트와 인라인 안내 발견',await page.locator('[data-pattern="toast"]').count()===1&&await page.locator('[data-pattern="banner"]').count()===1);
  await page.locator('#compare-mode').click();
  await page.locator('[data-compare="toast"]').check();await page.locator('[data-compare="banner"]').check();
  await page.screenshot({path:path.join(base,'03-상황-검색.png')});
  await page.locator('[data-open-compare]').click();
  check('두 패턴의 사용 조건·확인·위치·금기 비교',await page.locator('#compare-dialog .compare-row').count()===4);
  await page.screenshot({path:path.join(base,'04-패턴-비교.png')});
  await page.keyboard.press('Escape');
  check('비교를 닫고 비교 버튼으로 초점 복귀',await page.locator('[data-open-compare]').evaluate(el=>el===document.activeElement));
  await page.locator('[data-pattern="toast"] .card-main').click();
  check('제목으로 초점 진입',await page.locator('#detail-title').evaluate(el=>el===document.activeElement));
  const savedBefore=await page.evaluate(()=>state.saved.length);
  await page.locator('[data-demo="save"]').click();
  check('체험 안에서 저장 결과 표시',await page.locator('.demo-output').textContent().then(t=>t.includes('문서가 저장됐어요')));
  check('체험은 실제 패턴 저장에 영향 없음',await page.evaluate(()=>state.saved.length)===savedBefore);
  await page.locator('[data-detail-style="ink"]').click();
  check('예시 전체에 스타일 적용',await page.locator('.demo-stage').evaluate(el=>getComputedStyle(el).getPropertyValue('--p-radius').trim()==='2px'));
  await page.locator('#detail-save').click();
  await page.screenshot({path:path.join(base,'05-상세-체험과-저장.png')});
  await page.keyboard.press('Escape');
  check('상세를 닫고 원래 카드로 초점 복귀',await page.locator('[data-pattern="toast"] .card-main').evaluate(el=>el===document.activeElement));
  await page.locator('.top-nav [data-page="saved"]').click();
  check('패턴과 스타일의 조합 저장',await page.locator('.saved-item').count()===1&&await page.locator('.saved-copy').textContent().then(t=>t.includes('선화')));
  await page.reload();await page.locator('.top-nav [data-page="saved"]').click();
  check('새로고침 후 저장 유지',await page.locator('.saved-item').count()===1);
  check('저장한 패턴 제목이 상단에 유지',await page.locator('.saved-intro').evaluate(e=>e.getBoundingClientRect().top<180));
  await page.screenshot({path:path.join(base,'08-저장한-패턴.png')});
  await page.locator('.top-nav [data-page="styles"]').click();
  check('동일 기능의 세 스타일 비교',await page.locator('.focus-app').count()===3);

  await page.screenshot({path:path.join(base,'06-화면-전체-스타일.png')});
  for(const summary of await page.locator('.style-sources summary').all())await summary.click();
  await page.waitForFunction(()=>[...document.querySelectorAll('.style-sources[open] img')].every(e=>e.complete&&e.naturalWidth>0));
  check('세 스타일의 원본 참고 이미지 9장 열람',await page.locator('.style-sources[open] img').count()===9);
  await page.screenshot({path:path.join(base,'14-스타일-참고-이미지.png'),fullPage:true});
  for(const summary of await page.locator('.style-sources summary').all())await summary.click();
  await page.locator('[data-lab-clock="ink"]').click();
  await page.waitForFunction(()=>document.querySelector('.focus-ink .focus-clock').textContent!=='25:00');
  check('집중 타이머 시작과 시간 감소',await page.locator('[data-lab-clock="ink"]').getAttribute('aria-pressed')==='true');
  await page.locator('[data-lab-clock="ink"]').click();
  const pausedTime=await page.locator('.focus-ink .focus-clock').textContent();await page.waitForTimeout(1100);
  check('타이머 일시정지',await page.locator('.focus-ink .focus-clock').textContent()===pausedTime);
  await page.locator('[data-lab-duration="ink"][data-minutes="50"]').click();
  check('집중 시간 변경',await page.locator('.focus-ink .focus-clock').textContent()==='50:00');
  await page.locator('[data-lab-task="ink"][data-task-index="0"]').check();
  check('할 일 완료와 집계 연결',await page.locator('.focus-ink .task-count').textContent()==='2 / 2');
  await page.locator('[data-lab-view="form"]').click();
  for(const key of ['ink','block','calm']){
    await page.locator(`[data-lab-form="${key}"] [type=submit]`).click();
    check(`${key} 입력 오류와 초점`,await page.locator(`#collection-${key}`).getAttribute('aria-invalid')==='true'&&await page.locator(`#collection-${key}`).evaluate(e=>e===document.activeElement));
    await page.locator(`#collection-${key}`).fill('여름의 색');
    await page.locator(`[data-lab-form="${key}"] [type=submit]`).click();
    check(`${key} 입력 완료 피드백`,await page.locator(`[data-lab-form="${key}"] .lab-form-result`).textContent().then(t=>t.includes('여름의 색')));
  }
  await page.screenshot({path:path.join(base,'10-스타일-입력.png')});
  await page.locator('[data-lab-view="feedback"]').click();
  check('뷰 전환 후 초점 유지',await page.locator('[data-lab-view="feedback"]').evaluate(e=>e===document.activeElement));
  await page.locator('[data-lab-dismiss="block"]').click();
  check('예시 알림 닫기와 초점 복귀',await page.locator('[data-lab-toast="block"]').isHidden()&&await page.locator('[data-lab-feedback="block"]').evaluate(e=>e===document.activeElement));
  await page.locator('[data-lab-feedback="block"]').click();
  check('피드백 예시 다시 실행',await page.locator('[data-lab-toast="block"]').isVisible());
  await page.screenshot({path:path.join(base,'11-스타일-피드백.png')});
  await page.locator('[data-lab-view="form"]').click();
  check('예시 전환 후 입력 보존',await page.locator('#collection-ink').inputValue()==='여름의 색');
  await page.locator('[data-apply-style="block"]').click();
  check('컬러블록 16개 패턴에 적용',await page.locator('#pattern-grid .preview.theme-block').count()===16);
  await page.reload();
  check('새로고침 후 선택 스타일 유지',await page.locator('#preview-style').inputValue()==='block'&&await page.locator('#pattern-grid .preview.theme-block').count()===16);
  await page.screenshot({path:path.join(base,'12-컬러블록-패턴.png')});
  await page.locator('[data-pattern="tabs"] .card-main').click();await page.locator('#detail-save').click();await page.keyboard.press('Escape');
  await page.locator('.top-nav [data-page="saved"]').click();
  check('새 스타일 저장과 다시 열기',await page.locator('[data-saved-style="block"]').count()===1);
  await page.locator('[data-saved-style="block"]').click();
  check('저장한 컬러블록 스타일 복원',await page.locator('.demo-stage.theme-block').isVisible());await page.keyboard.press('Escape');
  await page.locator('[data-unsave-style="block"]').click();
  await page.locator('.top-nav [data-page="styles"]').click();
  await page.locator('[data-apply-style="clear"]').click();
  check('기본 스타일 복귀',await page.locator('#pattern-grid .preview.theme-clear').count()===16);
  await page.locator('.top-nav [data-page="styles"]').click();

  await page.locator('[data-apply-style="calm"]').click();
  check('선택 스타일이 모든 목록 미리보기에 반영',await page.locator('#pattern-grid .preview.theme-calm').count()===16);
  await page.locator('#query').fill('존재하지않는말xyz987');await page.locator('#search-form').evaluate(f=>f.requestSubmit());
  check('검색 실패에서 복구 행동 제공',await page.locator('#empty-results').isVisible());
  await page.locator('[data-reset]').click();check('초기화하면 16개 복구',await page.locator('.pattern-card').count()===16);
  await page.locator('#status').selectOption('error');check('상태 필터가 분류와 독립',await page.locator('.pattern-card').count()===3);
  await page.locator('#reset-filters').click();
  await page.locator('.top-nav [data-page="saved"]').click();await page.locator('[data-unsave]').click();
  check('저장 취소',await page.locator('.saved-item').count()===0);
  await page.locator('.top-nav [data-page="patterns"]').click();
  const named=await page.locator('button').evaluateAll(es=>es.filter(e=>e.offsetWidth&&e.offsetHeight).every(e=>(e.getAttribute('aria-label')||e.textContent).trim()));
  check('표시된 버튼에 이름 존재',named);
  await page.locator('#query').fill('저장');await page.locator('.top-nav [data-page="styles"]').click();await page.waitForTimeout(180);check('검색 직후 이동한 탭을 지연 검색이 바꾸지 않음',await page.locator('#style-page').isVisible());
  await page.locator('.top-nav [data-page="patterns"]').click();await page.locator('#reset-filters').click();
  await page.locator('[data-pattern="toast"] .card-main').click();
  for(let i=0;i<25;i++){await page.keyboard.press('Tab');assert.ok(await page.evaluate(()=>document.activeElement.closest('#detail-dialog')!==null),'모달 초점 이탈');}
  check('Tab 25회 이동에서 모달 초점 유지',true);
  await page.keyboard.press('Escape');
  await page.locator('[data-pattern="dialog"] .card-main').click();await page.locator('[data-demo="confirm"]').click();
  check('확인 예시가 실제 대화상자를 열고 취소 초점 제공',await page.locator('#demo-confirm-dialog').evaluate(e=>e.open)&&await page.locator('[data-demo="confirm-no"]').evaluate(e=>e===document.activeElement));
  await page.keyboard.press('Escape');check('중첩 예시를 닫아도 패턴 상세 유지',await page.locator('#detail-dialog').evaluate(e=>e.open));await page.keyboard.press('Escape');
  await page.locator('[data-pattern="tabs"] .card-main').click();await page.locator('#demo-tab-all').focus();await page.keyboard.press('ArrowRight');
  check('탭 방향키 이동과 패널 연결',await page.locator('#demo-tab-done').getAttribute('aria-selected')==='true'&&await page.locator('#demo-tab-panel').getAttribute('aria-labelledby')==='demo-tab-done');await page.keyboard.press('Escape');
  await page.locator('[data-pattern="stepper"] .card-main').click();await page.locator('#demo-name').fill('내 디자인');await page.locator('[data-demo="step"]').click();await page.locator('[data-demo="step-back"]').click();
  check('이전 단계로 돌아가도 입력 유지',await page.locator('#demo-name').inputValue()==='내 디자인');await page.keyboard.press('Escape');
  await page.locator('[data-pattern="form"] .card-main').click();await page.locator('[data-demo="validate"]').click();
  check('입력 오류가 해당 필드와 연결',await page.locator('#demo-email').getAttribute('aria-invalid')==='true'&&await page.locator('#demo-email').getAttribute('aria-describedby')==='demo-validation');
  await page.locator('#demo-email').fill('hello@example.com');await page.locator('[data-demo="validate"]').click();check('입력 수정 후 오류 해제',await page.locator('#demo-email').getAttribute('aria-invalid')==='false');await page.keyboard.press('Escape');
  await page.locator('[data-pattern="progress"] .card-main').click();await page.locator('[data-demo="progress"]').click();await page.waitForFunction(()=>document.querySelector('#demo-progress').value===100);
  check('진행 체험이 완료 상태에 도달',await page.locator('[data-demo="progress"]').isEnabled());await page.keyboard.press('Escape');
  for(const width of [320,390,768]){
    await page.setViewportSize({width,height:900});
    check(`${width}px에서 가로 넘침 없음`,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  }
  const mobile=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1});mobile.on('pageerror',e=>errors.push(e.message));
  await mobile.goto(pathToFileURL(path.join(base,'index.html')).href);
  await mobile.screenshot({path:path.join(base,'07-모바일-탐색.png')});
  const visibleCards=await mobile.locator('.pattern-card').evaluateAll(es=>es.filter(e=>{const r=e.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight}).length);
  check('390×844 첫 화면에 패턴 6개 전체 노출',visibleCards>=6);
  await mobile.locator('[data-pattern="toast"] .card-main').click();
  check('모바일 상세 가로 넘침 없음',await mobile.locator('#detail-dialog').evaluate(e=>e.scrollWidth<=e.clientWidth));
  await mobile.locator('[data-demo="save"]').click();
  await mobile.screenshot({path:path.join(base,'09-모바일-상세.png')});
  await mobile.keyboard.press('Escape');
  await mobile.locator('.top-nav [data-page="styles"]').click();
  await mobile.screenshot({path:path.join(base,'13-모바일-스타일.png'),fullPage:true});
  for(const width of [320,390,768]){
    await mobile.setViewportSize({width,height:844});
    for(const view of ['focus','form','feedback']){
      await mobile.locator(`[data-lab-view="${view}"]`).click();
      check(`${width}px ${view} 스타일 가로 넘침 없음`,await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
      check(`${width}px ${view} 예시 내용 잘림 없음`,await mobile.locator('.sample-app').evaluateAll(es=>es.every(e=>e.scrollHeight<=e.clientHeight+2&&e.scrollWidth<=e.clientWidth+2)));
    }
  }
  await mobile.close();
  await page.emulateMedia({reducedMotion:'reduce'});
  check('움직임 완화에서 카드 전환 제거',await page.locator('.pattern-card').first().evaluate(e=>getComputedStyle(e).transitionDuration==='0s'));
  check('실행 중 JavaScript 오류 없음',errors.length===0);
  const report={layoutMetrics:before,checkedAt:new Date().toISOString(),mobileFullyVisibleCards:visibleCards,browser:'Playwright Chromium, macOS',checks,passed:checks.length,errors,scope:'대표 패턴 16개, 세 스타일 계열과 기본, 집중·입력·피드백 예시, 선택 유지·저장, 화면 320/390/768/1440px',limitations:'사용자 연구·실기기 터치·스크린리더·전체 WCAG 적합성·전체 사전 구현 검증은 포함하지 않음'};
  fs.writeFileSync(path.join(base,'검증-결과.json'),JSON.stringify(report,null,2));
  console.log(JSON.stringify({passed:checks.length,errors,visibleCards}));
 }finally{await browser.close();}
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
