const {chromium,firefox,webkit}=require('playwright-core');
const assert=require('node:assert/strict');
const base=process.env.PATTOVE_TEST_URL||'http://127.0.0.1:4173/';
(async()=>{for(const [name,engine]of Object.entries({chromium,firefox,webkit})){
  const browser=await engine.launch();try{
    const page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(8000);
    await page.route('**/src/app.js',route=>route.fulfill({contentType:'text/javascript',body:''}));
    await page.goto(base);await page.waitForFunction(()=>window.Pattove?.parts);
    const stage=async(id,options={})=>{await page.evaluate(({id,options})=>{document.body.innerHTML='<main class="ds theme-main" data-style="main">'+Pattove.parts.renderItem(id,'test-one',options)+Pattove.parts.renderItem(id,'test-two',options)+'</main>';Pattove.mountParts(document.querySelector('main'));},{id,options});return page.locator('main');};
    const ids=await page.evaluate(()=>Pattove.systemRegistry.items.filter(i=>i.reactExport).map(i=>i.id));
    for(const id of ids){await stage(id);const issues=await page.evaluate(()=>{const ids=[...document.querySelectorAll('[id]')].map(n=>n.id),bad=[];if(new Set(ids).size!==ids.length)bad.push('duplicate');document.querySelectorAll('[aria-controls],[aria-describedby],[aria-labelledby],label[for]').forEach(n=>{for(const key of ['aria-controls','aria-describedby','aria-labelledby','for'])for(const id of (n.getAttribute(key)||'').split(/\s+/).filter(Boolean))if(!document.getElementById(id))bad.push(key+':'+id);});return bad;});assert.deepEqual(issues,[],name+' relationships '+id);assert(await page.locator('main').evaluate(n=>n.scrollWidth<=innerWidth+1),name+' mobile width '+id);}
    await page.evaluate(()=>{document.body.innerHTML='<main class="ds" data-style="main"><label for="bounded-stepper">수량</label>'+Pattove.parts.stepper({id:'bounded-stepper',value:1,min:0,max:2})+'</main>';Pattove.mountParts(document.querySelector('main'));window.stepChanges=0;document.querySelector('input').addEventListener('change',()=>window.stepChanges++);});
    await page.getByRole('button',{name:'하나 더하기'}).click();assert.equal(await page.getByLabel('수량').inputValue(),'2');assert(await page.getByRole('button',{name:'하나 더하기'}).isDisabled());await page.getByRole('button',{name:'하나 빼기'}).click();await page.getByRole('button',{name:'하나 빼기'}).click();assert.equal(await page.getByLabel('수량').inputValue(),'0');assert(await page.getByRole('button',{name:'하나 빼기'}).isDisabled());assert.equal(await page.evaluate(()=>window.stepChanges),3);
    await stage('combobox');const combo=page.getByRole('combobox').first();await combo.fill('부');await combo.press('ArrowDown');await combo.press('Enter');assert.equal(await combo.inputValue(),'부산');assert.equal(await combo.getAttribute('aria-expanded'),'false');await combo.fill('없는도시');assert(await page.getByText('일치하는 항목이 없어요.').isVisible());await combo.press('Escape');
    for(const id of ['dialog','confirmation-dialog','drawer']){await stage(id);const trigger=page.locator('[data-dialog-open]').first();await trigger.click();assert(await page.locator('dialog').first().evaluate(n=>n.open));await page.keyboard.press('Escape');await page.waitForFunction(()=>document.activeElement?.dataset.dialogOpen==='test-one');assert(await trigger.evaluate(n=>n===document.activeElement));await trigger.click();await page.locator('dialog').first().getByRole('button').first().click();assert(!(await page.locator('dialog').first().evaluate(n=>n.open)));}
    await stage('confirmation-dialog');await page.evaluate(()=>{window.closedValues=[];document.querySelector('main').addEventListener('pattove:dialogclose',e=>window.closedValues.push(e.detail.value));});
    await page.locator('[data-dialog-open]').first().click();await page.locator('dialog[open] button[value=confirm]').click();await page.waitForFunction(()=>window.closedValues.length===1);await page.locator('[data-dialog-open]').first().click();await page.keyboard.press('Escape');await page.waitForFunction(()=>window.closedValues.length===2);assert.deepEqual(await page.evaluate(()=>window.closedValues),['confirm','']);
    await stage('popover');await page.locator('[popovertarget]').first().click();assert(await page.locator('[popover]').first().isVisible());await page.keyboard.press('Escape');assert(!(await page.locator('[popover]').first().isVisible()));
    await stage('file-upload',{accept:'.txt',maxBytes:5});const file=page.locator('input[type=file]').first();await file.setInputFiles({name:'bad.txt',mimeType:'text/plain',buffer:Buffer.from('too large')});assert.equal(await file.getAttribute('aria-invalid'),'true');await file.setInputFiles({name:'ok.txt',mimeType:'text/plain',buffer:Buffer.from('ok')});assert.equal(await file.getAttribute('aria-invalid'),'false');
    await stage('pagination',{page:1,total:2});const nav=page.locator('.ds-pagination').first();assert(await nav.getByRole('button',{name:'이전'}).isDisabled());await nav.getByRole('button',{name:'다음'}).click();assert(await nav.getByRole('button',{name:'다음'}).isDisabled());assert.equal(await nav.locator('[role=status]').textContent(),'2 / 2');
    await stage('settings-form');await page.evaluate(()=>{let attempts=0;document.querySelector('form').addEventListener('pattove:submit',e=>{window.submitted=e.detail.values;e.detail.respondWith(++attempts===1?Promise.reject(Error('offline')):new Promise(resolve=>{window.completeSave=resolve;}));});});
    const form=page.locator('form').first();await form.getByLabel('표시 이름').fill('보존할 이름');await form.getByRole('button',{name:'저장'}).click();await form.getByRole('status').filter({hasText:'처리하지 못했어요.'}).waitFor();assert.equal(await form.getByLabel('표시 이름').inputValue(),'보존할 이름');await form.getByRole('button',{name:'저장'}).click();assert(await form.getByRole('button',{name:'저장'}).isDisabled());await page.evaluate(()=>window.completeSave());await form.getByRole('status').filter({hasText:'저장했어요.'}).waitFor();assert.equal(await page.evaluate(()=>window.submitted.name),'보존할 이름');
    await stage('settings-form');await page.evaluate(()=>{const form=document.querySelector('form');window.cancelCalls=0;form.addEventListener('pattove:submit',e=>{window.cancelCalls++;form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));e.detail.respondWith(new Promise(()=>{}));e.detail.abort();});});
    const cancelForm=page.locator('form').first();await cancelForm.getByRole('button',{name:'저장'}).click();await cancelForm.getByRole('status').filter({hasText:'취소했어요.'}).waitFor();assert(!(await cancelForm.getByRole('button',{name:'저장'}).isDisabled()));assert.equal(await page.evaluate(()=>window.cancelCalls),1);await cancelForm.getByRole('button',{name:'저장'}).click();assert.equal(await page.evaluate(()=>window.cancelCalls),2);
    await stage('login-form');const login=page.locator('form').first();await login.getByLabel('이메일').fill('person@example.com');await login.getByLabel('비밀번호').fill('secret-not-stored');await login.getByRole('button',{name:'로그인'}).click();assert((await login.getByRole('status').textContent()).includes('처리할 수 없어요'));assert(!(await page.evaluate(()=>JSON.stringify(localStorage))).includes('secret-not-stored'));
    await stage('input-result');const calc=page.locator('form').first();await calc.getByLabel('개당 금액').fill('15');await calc.getByLabel('수량').fill('3');await calc.getByRole('button',{name:'계산'}).click();assert((await calc.locator('output').textContent()).includes('45'));
    await stage('comparison');await page.locator('.ds-comparison').first().getByRole('button').nth(1).click();assert.equal(await page.locator('.ds-comparison').first().locator('[aria-pressed=true]').count(),1);
    await stage('article-page',{title:'긴 제목'.repeat(20),sections:[{title:'본문',body:'긴 내용 '.repeat(300)}]});await page.emulateMedia({media:'print'});assert(!(await page.locator('.ds-article nav').first().isVisible()));
    assert.deepEqual(errors,[]);console.log(name+': '+ids.length+' new parts, keyboard, forms, errors, offline export contracts passed');
  }finally{await browser.close();}
}})().catch(e=>{console.error(e);process.exitCode=1;});
