import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { spawn, execFile } from 'node:child_process';
import { promisify } from 'node:util';
import http from 'node:http';
import os from 'node:os';
import { fileURLToPath } from 'node:url';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { unzipSync } from 'fflate';
import sharp from 'sharp';
import {chromium} from 'playwright-core';
import { search, metadata, allIds, inventory, listPacks, packIds, asset, root, trimCache } from '../scripts/lib/illustration-store.mjs';
import { exportDirectory, exportZip } from '../scripts/lib/illustration-export.mjs';
const out=path.join(root,'test-results/illustration-tools');await fs.mkdir(out,{recursive:true});
let checks=0;const ok=(condition,message)=>{assert.ok(condition,message);checks++;};
const report={};
const run=promisify(execFile);
const cli=async(...args)=>JSON.parse((await run(process.execPath,['scripts/illustrations.mjs',...args],{cwd:root,maxBuffer:1024*1024})).stdout);
ok((await cli('search','material:yard')).items[0].id==='material:yard','CLI searches all subjects');
ok((await cli('get','material:yard')).canonicalId==='material:yard','CLI retrieves metadata');
ok((await cli('packs')).length===56,'CLI exposes all packs');
ok((await cli('status')).total===10908,'CLI reports complete catalog');
ok((await cli('export','--id','material:yard')).items===1,'CLI creates selected pack');
const ids=allIds();ok(ids.length===10908,'All subjects remain');
for(const id of ids) {const m=metadata(id);assert.equal(m.id,id);assert.ok(m.sourceHash?.length===64);assert.ok(m.assets.png&&m.assets.webp);}
ok(true,'Every ID resolves to a lossless source and PNG/WebP');
const pages=[];for(let offset=0;offset<ids.length;offset+=100)pages.push(...search({offset,limit:100}).items.map(i=>i.id));
assert.deepEqual(pages,ids);ok(true,'Paginated search enumerates every item exactly once');
ok(search({query:'검색'}).items.some(e=>e.id==='ICO-62'),'Korean search');
ok(search({query:'search'}).items.some(e=>e.id==='ICO-62'),'English search');
ok(search({query:'material:yard'}).items[0].id==='material:yard','Exact ID rank');
ok(listPacks().length===56,'Core pack plus 55 categories');
ok(new Set(listPacks().flatMap(p=>packIds(p.id))).size===10908,'Pack coverage complete');
for(const p of listPacks())for(const id of packIds(p.id))assert.ok(ids.includes(id));
for(const opts of [{limit:101},{offset:-1},{style:'missing'},{query:'x'.repeat(301)}])assert.throws(()=>search(opts));checks+=4;
for(const id of ['../manifest','https://example.com/a.png','unknown'])assert.throws(()=>metadata(id));checks+=3;
const a=await asset('ICO-01'),b=await asset('ICO-832');ok(a.key===b.key&&a.bytes.equals(b.bytes),'Aliases share one cached image');
for(const format of ['webp','png'])for(const size of [24,48,96,192,512]) {
  const result=await asset('material:yard',{format,size});const info=await sharp(result.bytes).metadata();
  ok(info.width===size&&info.height===size&&info.hasAlpha,format+' '+size);
}
await assert.rejects(()=>asset('ICO-62',{format:'svg'}));checks++;
const zip=await exportZip({ids:['ICO-01','ICO-832','material:yard']});
const files=unzipSync(await fs.readFile(zip.path));const manifest=JSON.parse(Buffer.from(files['manifest.json']));
ok(manifest.items.length===3&&Object.keys(files).filter(f=>f.startsWith('assets/')).length===2,'ZIP deduplicates aliases');
ok(!!files['Illustration.jsx']&&!!files['index.html'],'ZIP includes React and offline HTML');
ok(manifest.catalogRevision?.length===64&&manifest.items.every(item=>item.sourceHash?.length===64),'ZIP records catalog and source revisions');
const folder=path.join(out,'consumer-'+Date.now());await exportDirectory({ids:['ICO-62','material:yard']},folder);
await assert.rejects(()=>exportDirectory({ids:['ICO-62']},folder));checks++;
const prune=path.join(out,'prune');await fs.mkdir(prune,{recursive:true});
for(const char of ['a','b','c'])await fs.writeFile(path.join(prune,char.repeat(64)+'.webp'),Buffer.alloc(100));
await trimCache(prune,150);ok((await fs.readdir(prune)).length===1,'Cache evicts oldest files within its byte limit');
const transport=new StdioClientTransport({command:process.execPath,args:[path.join(root,'scripts/illustrations-mcp.mjs')],stderr:'pipe'});
const client=new Client({name:'pattove-test',version:'1.0.0'});
try {
  await client.connect(transport);const tools=await client.listTools();ok(tools.tools.length===5,'Official MCP transport exposes five tools');
  const result=await client.callTool({name:'search_illustrations',arguments:{query:'material:yard'}});
  ok(JSON.parse(result.content[0].text).items[0].id==='material:yard','MCP searches entire library');
  const preview=await client.callTool({name:'preview_illustration',arguments:{id:'material:yard'}});
  ok(preview.content[0].type==='image'&&preview.content[0].mimeType==='image/webp','MCP returns real preview');
  const exported=await client.callTool({name:'export_illustrations',arguments:{ids:['material:yard']}});
  ok(JSON.parse(exported.content[0].text).items===1,'MCP exports outside core UI');
  const rejected=await client.callTool({name:'get_illustration',arguments:{id:'../secret'}});
  ok(rejected.isError,'MCP rejects arbitrary paths');
}finally{await client.close();}
const port=4191,origin='http://127.0.0.1:'+port;
const server=spawn(process.execPath,['scripts/serve.cjs'],{cwd:root,env:{...process.env,PORT:String(port)},stdio:['ignore','pipe','pipe']});
const logs=[];server.stderr.on('data',d=>logs.push(String(d)));
let browser;const symlink=path.join(root,'src/icon-safety-test-link');
const outside=await fs.mkdtemp(path.join(os.tmpdir(),'pattove-safety-'));
await fs.writeFile(path.join(outside,'private.txt'),'outside fixture');
const linkType=process.platform==='win32'?'junction':'dir';
const unlink=async()=>{if(process.platform==='win32')await fs.rmdir(symlink);else await fs.unlink(symlink);};
try {
  let ready=false;for(let i=0;i<80;i++){try{if((await fetch(origin+'/__pattove/status')).ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,100));}ok(ready,'Local server starts');
  let response=await fetch(origin+'/api/illustrations/search?q=검색');ok(response.ok&&(await response.json()).total>0,'HTTP search');
  response=await fetch(origin+'/api/illustrations/asset?id=material%3Ayard&format=png&size=512');
  ok(response.ok&&response.headers.get('content-type')==='image/png','HTTP PNG generated from source');
  const etag=response.headers.get('etag');
  response=await fetch(origin+'/api/illustrations/asset?id=material%3Ayard&format=png&size=512',{headers:{'If-None-Match':etag}});
  ok(response.status===304,'ETag avoids repeated transfer');
  for(const suffix of ['/api/illustrations/asset?id=ICO-62&size=999999','/api/illustrations/asset?id=ICO-62&format=svg','/api/illustrations/search?limit=999'])ok((await fetch(origin+suffix)).status===400,'Reject unbounded/image format request');
  ok((await fetch(origin+'/api/illustrations/search',{headers:{Origin:'https://attacker.example'}})).status===403,'Cross-origin API denied');
  const badHostStatus=await new Promise((resolve,reject)=>{http.get(origin+'/api/illustrations/search',{headers:{Host:'attacker.example'}},response=>{response.resume();resolve(response.statusCode);}).on('error',reject);});
  ok(badHostStatus===403,'DNS rebinding host denied');
  await fs.symlink(outside,symlink,linkType);
  ok((await fetch(origin+'/src/icon-safety-test-link/private.txt')).status===403,'Symlink escape denied');
  ok((await fetch(origin+'/assets/icons/illustrated/production.json')).status===404,'Production metadata not published');
  const source=JSON.parse(await fs.readFile(path.join(root,'assets/icons/illustrated/manifest.json'))).batches[0].source;
  ok((await fetch(origin+'/'+source)).status===404,'Original source objects not published');
  await unlink();await fs.symlink(path.dirname(path.join(root,source)),symlink,linkType);
  ok((await fetch(origin+'/src/icon-safety-test-link/'+path.basename(source))).status===403,'Symlink to private source object denied');
  response=await fetch(origin+'/src/data/library.js');
  ok(response.headers.get('content-encoding')==='gzip','Browser catalog is compressed in transit');
  const searchBytes=Buffer.byteLength(JSON.stringify(search({query:'검색',limit:10})));
  const fullCatalog=(await fs.stat(path.join(root,'src/data/library.js'))).size;
  report.aiSearchBytes=searchBytes;report.oldFullCatalogBytes=fullCatalog;
  browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(origin+'/#/dictionary?shelf=icon');
  await page.locator('.dict-entry.is-illustrated img').first().evaluate(n=>n.decode());
  await page.locator('[data-library-entry="ICO-01"]').click();
  await page.locator('[data-pick-illustration="ICO-01"]').click();await page.keyboard.press('Escape');
  ok((await page.locator('[data-export-selected]').textContent()).includes('1개'),'User selects a custom pack');
  const download=page.waitForEvent('download');await page.locator('[data-export-selected]').click();ok((await download).suggestedFilename().endsWith('.zip'),'Selected pack download');
  await page.locator('[data-export-selected]:not([aria-busy])').waitFor();
  await page.screenshot({path:path.join(out,'packs-desktop.png')});
  await page.setViewportSize({width:375,height:900});ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Pack tools fit mobile');
  await page.screenshot({path:path.join(out,'packs-mobile.png')});
  const offline=await browser.newPage();await offline.route('http**',route=>route.abort());await offline.goto(new URL('index.html',new URL('file://'+folder+'/')).href);
  ok(await offline.locator('img').evaluateAll(async nodes=>{await Promise.all(nodes.map(n=>n.decode()));return nodes.length===2&&nodes.every(n=>n.naturalWidth===512);}), 'Exported images work offline');
  assert.deepEqual(errors,[]);checks++;
} finally {await browser?.close();server.kill();await unlink().catch(()=>{});await fs.unlink(path.join(outside,'private.txt'));await fs.rmdir(outside);await fs.writeFile(path.join(out,'server.log'),logs.join(''));}
await fs.writeFile(path.join(out,'results.json'),JSON.stringify({checks,...report},null,2));
console.log(checks+' illustration management checks passed; all '+ids.length+' IDs covered.');
