"""Bundle project SVGs for offline use and inherited theme colors."""
import json
from pathlib import Path
from xml.etree import ElementTree as ET

root = Path(__file__).resolve().parent.parent
ET.register_namespace('', 'http://www.w3.org/2000/svg')
icons = {}
for source in sorted((root / 'assets/icons').glob('*.svg')):
    svg = ET.parse(source).getroot()
    svg.set('class', 'ui-icon')
    svg.set('stroke', 'currentColor')
    svg.set('width', '20')
    svg.set('height', '20')
    svg.set('aria-hidden', 'true')
    svg.set('data-src', f'assets/icons/{source.name}')
    icons[source.stem] = ET.tostring(svg, encoding='unicode')
target = root / 'src/ui/icons.js'
target.write_text('// Generated by scripts/build-icons.py from assets/icons/*.svg.\n'
                  + 'window.Pattove.iconMarkup = ' + json.dumps(icons, indent=2) + ';\n', encoding='utf-8')
print(f'{len(icons)} project icons bundled.')
